language: ruby
rvm:
- 2.3.1
- 2.2.0
- 2.1.0
- 2.0.0
- 1.9.3
script:
 - bundle exec rspec spec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b034ea2dbc919b02f7
    on_success: change
    on_failure: change
    on_start: false