language: ruby
rvm:
- 2.3.1
- 2.2.0
- 2.1.0
- 2.0.0
- 1.9.3
script:
 - 'rspec spec'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b034ea2dbc919b02f7
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install git -y
sudo: false