language: ruby
rvm:
- 2.1.0
- 1.9.3
script:
 - 'rspec spec/git_fame_spec.rb --format documentation'
notifications:
  webhooks:
    urls:
      # to add your webhook go to travis and integrate gitter. now it link to f1yegor/git-fame-rb
      - https://webhooks.gitter.im/e/f78d9bd911568f4ff5d5
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
